# Generated by Django 3.0.7 on 2020-07-04 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição do tipo de pedido')),
                ('tipo', models.CharField(max_length=1, verbose_name='Tipo do pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name="Product's description")),
                ('status', models.BooleanField(default=True, verbose_name="Product's active")),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name="Product's price")),
                ('priceDate', models.DateTimeField(verbose_name='Price date')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='User namer')),
                ('description', models.CharField(max_length=100, verbose_name='User description')),
                ('lastLogin', models.DateTimeField(verbose_name='User last login date')),
                ('admin', models.BooleanField(default=False, verbose_name='User is admin')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justification', models.CharField(max_length=150, verbose_name='Order justification')),
                ('date', models.DateTimeField(verbose_name='Order date')),
                ('orderType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frigobar.OrderType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frigobar.User')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantity sale')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Sale price')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frigobar.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frigobar.Product')),
            ],
        ),
    ]
