# Generated by Django 3.0.7 on 2020-06-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição do produto')),
                ('ativo', models.BooleanField(default=True, verbose_name='Produto esta ativo')),
                ('preço', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Preço do produto')),
                ('data_preco', models.DateTimeField(verbose_name='Data do preço')),
            ],
        ),
    ]
