# Generated by Django 3.0.7 on 2020-06-28 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frigobar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Usuário')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição Extra')),
                ('ultimo_login', models.DateTimeField(verbose_name='Data do ultimo login do usuário')),
                ('admin', models.BooleanField(default=False, verbose_name='Identifica se é adminsitrador')),
            ],
        ),
    ]
