# Generated by Django 3.0.7 on 2020-06-29 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frigobar', '0002_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição do tipo de pedido')),
                ('tipo', models.CharField(max_length=1, verbose_name='Tipo do pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justificativa', models.CharField(max_length=150, verbose_name='Justificativa')),
                ('data', models.DateTimeField(verbose_name='Data do Pedido')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frigobar.TipoPedido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frigobar.Usuario')),
            ],
        ),
    ]
