# Generated by Django 3.0.7 on 2020-07-05 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frigobar', '0002_auto_20200704_2259'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderType',
        ),
    ]
