# Generated by Django 3.0.7 on 2020-06-29 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frigobar', '0003_pedido_tipopedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade vendida')),
                ('preco', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Preço de venda')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frigobar.Pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frigobar.Produto')),
            ],
        ),
    ]
