# Generated by Django 3.0.7 on 2020-07-20 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frigobar', '0006_auto_20200719_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='0', max_length=100, verbose_name='User name'),
            preserve_default=False,
        ),
    ]
