# Generated by Django 3.0.7 on 2020-07-20 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frigobar', '0008_user_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Last name'),
        ),
    ]
