# Generated by Django 3.0.7 on 2020-08-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frigobar', '0009_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('order_id', 'product_id')},
        ),
    ]
