# Generated by Django 3.0.7 on 2020-08-24 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frigobar', '0011_auto_20200809_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barCode',
            field=models.CharField(default='0', max_length=13, verbose_name="Product's barcode"),
            preserve_default=False,
        ),
    ]
