# Generated by Django 3.0.7 on 2020-10-21 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frigobar', '0012_product_barcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photoType', models.IntegerField()),
                ('directory', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Photo directory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='frigobar.Product')),
            ],
        ),
    ]
