# Generated by Django 3.0.7 on 2020-10-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frigobar', '0013_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='directory',
            field=models.FilePathField(blank=True, default=None, null=True, verbose_name='Photo directory'),
        ),
    ]
